# camera
width: 1920
height: 1080
ppx: 9.6591498e+02
ppy: 5.4094659e+02
fx: 1.3821929e+03
fy: 1.3783481e+03
coeffs: [0., 0., 0., 0., 0.]

# circle board
symmetric: false
num_circle_x: 7
num_circle_y: 7
circle_size: 0.03  # size in meter

# aruco markers
marker_size: 0.2  # size in meter
